/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 26-Sept.-2015 10:29:28 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

create database bas_registro_academico;

DROP TABLE IF EXISTS `registro_academico` CASCADE
;

DROP TABLE IF EXISTS `usuarios` CASCADE
;

CREATE TABLE IF NOT EXISTS `registro_academico` (
  `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT 'Identificador Autonumerico'   ,
  `sitio` varchar(100) NOT NULL COMMENT 'Nombre de la cidad',
  `sede` varchar(200) DEFAULT NULL COMMENT 'Nombre de la sede',
  `programa_academico` varchar(100) DEFAULT NULL COMMENT 'Nombre de programa academico',
  `semestre` varchar(100) DEFAULT NULL COMMENT 'Nombre del semestre',
  `materia` varchar(100) DEFAULT NULL COMMENT 'Nombre de la materia',
  `fecha` varchar(10) DEFAULT NULL COMMENT 'Fecha de clase',
  `hora_inicial` varchar(10) DEFAULT NULL COMMENT 'Hora Inicio',
  `hora_final` varchar(100) DEFAULT NULL COMMENT 'Hora Fin',
  CONSTRAINT `PK_REG_ACADEMICO` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla que almacena registro academico.';

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INTEGER NOT NULL AUTO_INCREMENT COMMENT 'Identificador Autonumerico'   ,
  `usuario` varchar(40) NOT NULL COMMENT 'Nombre del usuario',
  `password` varchar(40) NOT NULL COMMENT 'Contraseña',
  `fecha_hora` TIMESTAMP DEFAULT CURRENT_TIMESTAMP  COMMENT 'Fecha de ingreso',
  CONSTRAINT `PK_REG_ACADEMICO` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Tabla que almacena usuarios e ingresos.';

/*Se ingresa el usuario que se quiere usar*/
INSERT INTO usuarios values (2,'prueba','prueba123',CURRENT_TIMESTAMP);